### ISSUE TITLE
Add Travis-CI build

### ISSUE THREAD

**Issue by dgomesbr** [halysongoncalves/pugnotification#1]
self explanatory.

**Comment by dgomesbr** [comment]
it's failing:

```
FAILURE: Build failed with an exception.
* What went wrong:
Could not evaluate onlyIf predicate for task ':pugnotification:signArchives'.
> Unable to retrieve secret key from key ring file '/home/halyson/.gnupg/secring.gpg' as it does not exist
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

Explanation: http://stackoverflow.com/questions/9338428/using-secret-api-keys-on-travis-ci

**Comment by halysongoncalves** [comment]
@dgomesbr Meu querido, consegue configurar o travis novamente? E caso de algum problema ao assinar o artefato te passo key de release.
Abs!

**Comment by dgomesbr** [comment]
Opa, tudo bem? 

Dá uma olhada lá `https://travis-ci.org/halysongoncalves/pugnotification`, estou sem o SDK aqui no note, adicione o arquivo `.travis.yml` com o conteudo abaixo na raiz do projeto.

``` yml
language: android

android:
  components:
    - build-tools-20.0.0
    - android-17
  licenses:
    - android-sdk-license-5be876d5

jdk:
  - oraclejdk7
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "K6cyrlYhMmCHeez4uwkcQ5QeRLdCiegbbHnj8qKzbgcu0cDsvr2mMr6LLtjMOay1KMaxrW3QBFqz5nzTs/X0UnLl8jnt0Qdsf44BlIIZcJ9oldXFKAAWUZ3wlHTdz8ll+EBA31O1hkjAqRY4RDvS1hk842pRxXae3Dfodnjhz24="
    - secure: "pOUA/hwXvpwt7VeRIoAZPiIn2qc88c8/sx1AhN3YhSyCiERLEtuxZqFmCgZE/80U41sBlvg75lpvXpEsND4eriYiRNMDPyD7el2NYxTzseWAykZYe1+Gaeiq1mO83w4pTI7QUrrkU/9+rl9Ccqe6E0heER510ERyLH0nGb8vaRM="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
```
